;TITLE   "ZIP/6809-C INFOCOM, INC. --- INITIALIZATION"

; -------------------------------
; ZIP/6809 VERSION C
; Z-CODE INTERPRETER PROGRAM
; FOR CUBIX
; -------------------------------

; COMPANY PRIVATE -- NOT FOR DISTRIBUTION

DEBUG           = 0                               ; ASSEMBLY FLAG

; -----------
; ERROR CODES
; -----------

; 00 -- INSUFFICIENT RAM
; 01 -- ILLEGAL X-OP
; 02 -- ILLEGAL 0-OP
; 03 -- ILLEGAL 1-OP
; 04 -- ILLEGAL 2-OP
; 05 -- Z-STACK UNDERFLOW
; 06 -- Z-STACK OVERFLOW
; 07 -- ILLEGAL PROPERTY LENGTH (GETP)
; 08 -- DIVISION BY ZERO
; 09 -- ILLEGAL ARGUMENT COUNT (EQUAL?)
; 10 -- ILLEGAL PROPERTY ID (PUTP)
; 11 -- ILLEGAL PROPERTY LENGTH (PUTP)
; 12 -- DISK ADDRESS OUT OF RANGE
; 13 -- PARSER OVERFLOW
; 14 -- DRIVE ACCESS
; 15 -- Z-STACK DESTROYED
; 16 -- ZIP NOT FULLY LOADED

        ORG     $2000

RS1:
        CLRA                                      ; USE PAGE ZERO
        TFR     A,DP                              ; AS THE DIRECT PAGE
        LDS     #MSTACK                           ; GIVE THE STACK A NEW HOME
        JMP     COLD                              ; PERFORM ONE-TIME INITIALIZATION
RS1E:
        RMB     $100-(RS1E-RS1)


MSTART: ; START OF FREE PROGRAM RAM

        INCLUDE eq.asm
        INCLUDE warm.asm

;TITLE "ZIP/6809-B INFOCOM, INC. --- MAINLINE"
        INCLUDE MAIN.ASM
        INCLUDE SUBS.ASM
        INCLUDE DISPATCH.ASM

;TITLE "ZIP/6809-B INFOCOM, INC. --- OPCODE EXECUTORS"
        INCLUDE OPS0.ASM
        INCLUDE OPS1.ASM
        INCLUDE OPS2.ASM
        INCLUDE OPSX.ASM
        INCLUDE READ.ASM

;TITLE "ZIP/6809-B INFOCOM, INC. --- OPCODE SUPPORT"
        INCLUDE PAGING.ASM
        INCLUDE ZSTRING.ASM
        INCLUDE OBJECTS.ASM

;TITLE "ZIP/6809-B INFOCOM, INC. --- CUBIX DEPENDENT"
        INCLUDE IO.ASM
        INCLUDE SCREEN.ASM
        INCLUDE DISK.ASM

;TITLE "ZIP/6809-B INFOCOM, INC."
        IF      DEBUG
            INCLUDE BUGGER.ASM
        ENDIF

        END
